PlaySound ../../Data/Common/Sfx/Basedrop.wav  -43.864 3.945 28.644

//SetCameraFov 50

//CreateEntity
SetAmbientLight  1.0  0.0  0.0
sleep 0.01
SetAmbientLight  0.9  0.0  0.0
sleep 0.01
SetAmbientLight  0.8  0.0  0.0
sleep 0.01
SetAmbientLight  0.7  0.0  0.0
sleep 0.01
SetAmbientLight  0.6  0.0  0.0
sleep 0.01
SetAmbientLight  0.5  0.0  0.0
sleep 0.01
SetAmbientLight  0.4  0.0  0.0
sleep 2
SetAmbientLight  0.7 0.7 0.7



// Create a spider
//CreateEntity Auto Spider -43.864 3.945 28.644